version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "postgresql://USER:PASSWORD@db:5432/DATABASE_NAME"
      JWT_SECRET: "your_jwt_secret"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: USER
      POSTGRES_PASSWORD: PASSWORD
      POSTGRES_DB: DATABASE_NAME
    ports:
      - "5432:5432"